name: Wsam-Forge
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile Dylib
        run: |
          echo "🔥 بدء الصهر..."
          export SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          
          # تغيير اسم أي ملف mm موجود إلى wsam.mm لتجنب أخطاء الأسماء
          mv *.mm wsam.mm
          
          clang -dynamiclib -arch arm64 wsam.mm -o Wsam_Weapon.dylib -isysroot $SDK_PATH -framework Foundation -framework UIKit -framework CoreGraphics -framework QuartzCore -fobjc-arc
          echo "✅ تم الصهر بنجاح!"

      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: Wsam-Dylib
          path: Wsam_Weapon.dylib
